name: 'Browser in GitHub' (1)
on: workflow_dispatch

jobs:
  browse:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Browser
        run: |
          sudo apt update
          sudo apt install -y xvfb x11vnc novnc fluxbox firefox
          export DISPLAY=:1
          Xvfb :1 -screen 0 1024x768x16 &
          fluxbox &
          x11vnc -display :1 -forever -nopw -rfbport 5900 &
          websockify --web /usr/share/novnc 6080 localhost:5900 &
      - name: Keep Alive
        run: sleep 10h (2)
